name: Checks

on: workflow_call

jobs:

  version-check-job:
    name: Version Check
    runs-on: ubuntu-latest

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0
        with:
          poetry-version: 2.0.1

      - name: Check Version(s)
        run: poetry run version-check version.py

  build-documentation-job:
    name: Build Documentation
    needs: [version-check-job]
    runs-on: ubuntu-latest

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0
        with:
          poetry-version: 2.0.1

      - name: Build Documentation
        run: |
          poetry run python -m nox -s docs:build

  lint-job:
    name: Linting (Python-${{ matrix.python-version }})
    needs: [version-check-job]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0
        with:
          poetry-version: 2.0.1
          python-version: ${{ matrix.python-version }}

      - name: Run Tests
        run: poetry run nox -s lint:code

  type-check-job:
    name: Type Checking (Python-${{ matrix.python-version }})
    needs: [version-check-job]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0
        with:
          poetry-version: 2.0.1
          python-version: ${{ matrix.python-version }}

      - name: Run Tests
        run: poetry run nox -s lint:typing

  tests-job:
    name: Tests (Python-${{ matrix.python-version }})
    needs: [build-documentation-job, lint-job, type-check-job]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      python-version: ${{ matrix.python-version }}
