name: CI/CD

on:
  push:
    tags:
      - '**'

jobs:

  check-tag-version-job:
    name: Check Release Tag
    uses: workflows/check-release-tag.yml@0.6.2

  ci-job:
    name: Checks
    needs: [ check-tag-version-job ]
    uses: workflows/checks.yml@0.6.2

  cd-job:
    name: Continues Delivery
    needs: [ ci-job ]
    uses: workflows/build-and-publish.yml@0.6.2
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  metrics:
    needs: [ ci-job ]
    uses: workflows/report.yml@0.6.2
