name: CI

on:
  push:
    branches-ignore:
      - "github-pages/*"
      - "gh-pages/*"
      - "main"
      - "master"
  pull_request:
    types: [opened, reopened]
  schedule:
    # “At 00:00 on every 7th day-of-month from 1 through 31.” (https://crontab.guru)
    - cron: "0 0 1/7 * *"

jobs:

  ci-job:
    name: Checks
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  slow-tests:
    needs: [ ci-job ]
    uses: ./.github/workflows/slow-tests.yml

  metrics:
    needs: [ slow-tests ]
    uses: ./.github/workflows/report.yml

  branch-protection:
    needs: [ slow-tests ]
    uses: ./.github/workflows/branch-protection.yml
    # return 0
    # comment: just to enable separate step without any matrix to set up a
    # proper branch protection to ensure also slow-tests have been executed
    # successfully before merging to main branch
