name: CI

on:
  push:
    branches-ignore:
      - "github-pages/*"
      - "gh-pages/*"
      - "main"
      - "master"
  pull_request:
    types: [opened, reopened]
  schedule:
    # “At 00:00 on every 7th day-of-month from 1 through 31.” (https://crontab.guru)
    - cron: "0 0 1/7 * *"

jobs:

  ci-job:
    name: Checks
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  metrics:
    needs: [ ci-job ]
    uses: ./.github/workflows/report.yml

  gate-1:
    name: Regular
    needs: [ ci-job ]
    runs-on: ubuntu-latest
    steps:
      - name: Branch Protection
        run: true

  slow-tests:
    uses: ./.github/workflows/run-tests.yml
    environment:
      slow-tests
    secrets: inherit
    with:
      slow-tests: true
      python-version: "3.10"

  gate-2:
    name: Merge
    runs-on: ubuntu-latest
    needs: [ slow-tests ]
    steps:
      - name: Branch Protection
        run: true
