name: CI

on:
  push:
    branches-ignore:
      - "github-pages/*"
      - "gh-pages/*"
      - "main"
      - "master"

jobs:

  ci-job:
    name: Checks
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  metrics:
    needs: [ ci-job ]
    uses: ./.github/workflows/report.yml

  gate-1:
    name: Gate 1 - Regular CI
    needs: [ ci-job ]
    runs-on: ubuntu-24.04
    steps:
      - name: Branch Protection
        run: true

  slow-test-detection:
    name: Run Slow or Expensive Tests (e.g. SaaS)?
    runs-on: ubuntu-24.04
    steps:
      - name: Detect Slow Tests
        run: true
    environment:
      slow-tests

  run-slow-tests:
    name: Run Slow or Expensive Tests (e.g. SaaS) if Requested
    uses: ./.github/workflows/run-tests.yml
    needs: [ slow-test-detection ]
    secrets: inherit
    with:
      slow-tests: true
      python-version: "3.10"

  gate-2:
    name: Gate 2 - Allow Merge
    runs-on: ubuntu-24.04
    needs: [ run-slow-tests ]
    steps:
      - name: Branch Protection
        run: true
