name: PR-Merge

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:

  ci-job:
    name: Checks
    uses: workflows/checks.yml@0.6.2

  publish-docs:
    name: Publish Documentation
    uses: workflows/gh-pages.yml@0.6.2

  metrics:
    needs: [ ci-job ]
    uses: workflows/report.yml@0.6.2
