name: Run Tests

on:
  workflow_call:
    inputs:
      slow-tests:
        type: boolean
        default: false
      python-version:
        type: string
        required: true

jobs:

  tests-job:
    runs-on: ubuntu-24.04

    steps:
      - name: Set pytest markers
        id: pytest-markers
        if: ${{ ! inputs.slow-tests }}
        run: echo slow-tests='-m "not slow"' >> "$GITHUB_OUTPUT"

      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@1.0.1
        with:
          poetry-version: 2.0.1
          python-version: ${{ inputs.python-version }}

      - name: Run Tests and Calculate Coverage
        env:
          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
          PYTEST_ADDOPTS: '-o log_cli=true -o log_cli_level=INFO ${{ steps.pytest-markers.outputs.slow-tests }}'
        run: |
          echo "PYTEST_ADDOPTS = $PYTEST_ADDOPTS"
          export PROJECT_SHORT_TAG=$(poetry run -- nox -s project:get-short-tag)
          poetry run -- nox -s test:coverage --

      - name: Set coverage name
        id: coverage-suffix
        if: ${{ ! inputs.slow-tests }}
        run: |          
          if [ "${{ inputs.slow-tests }}" == "true" ]; then
            echo value='fast' >> "$GITHUB_OUTPUT"
          else
            echo value='slow' >> "$GITHUB_OUTPUT"
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage-python${{ inputs.python-version }}-${{ steps.coverage-suffix.outputs.value }}
          path: .coverage
          include-hidden-files: true