name: Checks

# Calls workflow/run-tests.yml without any matrix but including slow tests.

on:
  workflow_call:
  pull_request_target:
    types:
      - labeled

jobs:
  tests-job:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      slow-tests: true
      python-version: "3.10"
