name: Checks

# Calls workflow/run-tests.yml without any matrix but including slow tests.

on:
  workflow_call:
  pull_request_target:
    types:
      - labeled

jobs:
  eval-label:
    runs-on: ubuntu-latest
    steps: 
        - name: Display label
          run: |
            echo ${{ github.event.label.name }}
            echo ${{ github.event.label.name == 'slow-tests' }}

  tests-job:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      slow-tests: true
      python-version: "3.10"
