name: Checks

on: workflow_call

jobs:
  tests-job:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      slow-tests: true
      python-version: "3.10"
      exasol-version: "7.1.9"
