name: Checks

# Calls workflow/run-tests.yml without any matrix but including slow tests.

on: issue_comment

jobs:
  tests-job:
    # The first condition limits to consider only comments on pull requests
    # rather than on GitHub issues.
    if: ${{ github.event.issue.pull_request &&
            contains(github.event.comment.body, '[run-slow-tests]') }}
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      slow-tests: true
      python-version: "3.10"

  branch-protection:
    name: Gate 2 (Allow Merge)
    needs: [ tests-job ]
    uses: ./.github/workflows/branch-protection.yml
