name: Checks

# Calls workflow/run-tests.yml without any matrix but including slow tests.

on:
  workflow_call:
  pull_request:
    types: [ labeled ]

jobs:
  display-pr-label:
    runs-on: ubuntu-latest
    steps:
        - name: Display Pull Request Label
          run: |
            echo ${{ github.event.label.name }}
            echo ${{ github.event.label.name == 'slow-tests' }}

  tests-job:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      slow-tests: ${{ github.event.label.name == 'slow-tests' }}
      python-version: "3.10"
